# Generated by Django 5.2.8 on 2025-11-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
