# Generated by Django 5.2.8 on 2025-12-15 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_b', '0002_alter_driver_name_alter_driver_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='current_location',
        ),
        migrations.AddField(
            model_name='branch',
            name='coordinates',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='driver',
            name='coordinates',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizza_b.user'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='default_pizza.png', upload_to='pizzas/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_coordinates',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza_b.pizza'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
