# Generated by Django 5.2.8 on 2025-11-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_b', '0003_alter_pizza_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.TextField(),
        ),
    ]
